[package]
name = "provisioner"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
clap = "3.0.0-beta.5"
cmd_lib = "1.3.0"
color-eyre = "0.5.11"
copy_dir = "0.1.2"
once_cell = "1.8.0"
reqwest = { version = "0.11.6", features = ["json", "blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
