[package]
name = "provisioner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
cmd_lib = "1.3.0"
color-eyre = "0.5.11"
copy_dir = "0.1.2"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
