[package]
name = "provisioner"
version = "0.3.3"
edition = "2021"
description = "Provision Mammoth-ready Minecraft clusters with ease!"

[dependencies]
bytes = "1.1.0"
clap = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
cmd_lib = "1.3.0"
color-eyre = "0.5.11"
copy_dir = "0.1.2"
fs_extra = "1.2.0"
once_cell = "1.8.0"
reqwest = { version = "0.11.6", features = ["json", "blocking"] }
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"
toml = "0.5.8"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
